### ISSUE TITLE
Cannot build 

### ISSUE THREAD

**Issue by Oleg26Dev** [gigya/microdot#90]
I have tried to build the package with VS2015 and VS2017. 
In both cases many errors. 
What I am doing wrong?

**Comment by tsibelman** [comment]
It compiles using VS2017 if you could attach logs it would help to investigate.

**Comment by Oleg26Dev** [comment]
Ok, there is the log
[microdot_log.txt](https://github.com/gigya/microdot/files/1364403/microdot_log.txt)

**Comment by tsibelman** [comment]
It looks to me that you missing dependencies to take them you should run .paket/restore.bat  we have a guide of how to compile the library, please take a look, https://github.com/gigya/microdot/wiki/Contribution-Guide.

**Comment by Oleg26Dev** [comment]
Yes, 
========== Build: 17 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

I thought that Restore NuGet packages is enough.
Thank you, it was my mistake.

**Comment by tsibelman** [comment]
It an easy mistake to make, we use a paket client tools for nuggets management, that are not integrated into VS by default.

**Comment by Oleg26Dev** [comment]
Btw, are there any examples how to use the framework?
What is the best practice?
